# Generated by Django 4.0.4 on 2023-06-10 21:16

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'default_permissions': (), 'verbose_name': 'profil', 'verbose_name_plural': 'profile'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='previous_block_hash',
        ),
        migrations.AddField(
            model_name='block',
            name='mined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='previous_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(to='main.transaction'),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
