# Generated by Django 4.0.4 on 2023-06-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
        ),
    ]
