# Generated by Django 4.0.4 on 2023-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_block_previous_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.BigIntegerField(null=True),
        ),
    ]
