# Generated by Django 4.2.2 on 2023-06-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_block_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
