# Generated by Django 4.2.2 on 2023-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_vote_block_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
