# Generated by Django 4.2.2 on 2023-06-14 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 14, 16, 22, 36, 659518, tzinfo=datetime.timezone.utc)),
        ),
    ]
